### ISSUE TITLE
Can't change cid

### ISSUE THREAD

**Issue by spidget** [ccman32/FireRTCCallerIDChanger#1] opened 2017-09-25 00:52 UTC
Whenever I try to change my cid it gives me an error saying I'm missing a .dll file and this shows up in my clipboard.

```Unable to open file: C:\Users\quack\AppData\Local\Temp\573a54e0-852c-4119-8afd-62f8cb9338f7.txt.js

  phantomjs://code/bootstrap.js:113 in __die
Unable to load script C:\Users\quack\AppData\Local\Temp\573a54e0-852c-4119-8afd-62f8cb9338f7.txt.js; check file syntax

  phantomjs://code/bootstrap.js:113 in __die
```
Even though I tried getting the file and putting it where the exe is it doesn't want to work.

**Comment by ccman32** [comment] 2017-09-25 16:28
Which file does it say is missing? If it the file name is something like "msvcr110.dll" or "msvcp110.dll", try to download and install the [Visual C++ Redistributable für Visual Studio 2012 Update 4](https://www.microsoft.com/de-de/download/details.aspx?id=30679) (x86 and x64).
If that does not help, please provide me as much information as possible about the error you are getting (error messages, screenshots, ...) so I can provide better troubleshooting steps.

**Comment by spidget** [comment] 2017-09-25 19:18
I tried that already actually. Forgot to mention that. Its giving me another error though. It says "The application was unable to start correctly (0xc000007b). Click OK to close the application.

**Comment by ccman32** [comment] 2017-09-25 19:43
But which application is giving that error?

**Comment by spidget** [comment] 2017-09-25 20:00
php.exe

**Comment by ccman32** [comment] 2017-09-25 20:14
php.exe is an application that is used by another application which is used by my application. Therefore this is out of my hands because the problem is not directly caused by my application.
One thing I'd suggest is to download the latest PHP release from [here](http://windows.php.net/download/).
Then navigate into the folder to which you installed the FireRTC Caller ID Changer, open the "TagUI" folder and afterwards open the "src" folder.
Inside of the "src" folder you should find a folder "php". Open it, delete all files and folders in it and replace them with the files from the zip archive that you downloaded.
Please let me know if that helps or if the problem persists.

EDIT: By the way, are you trying to run it on a 32 bit Windows or is it a 64 bit version?

**Comment by spidget** [comment] 2017-09-25 20:22
Now its saying "TagUI has not been found in the startup directory of this
program! Exiting..."

**Comment by ccman32** [comment] 2017-09-25 20:24
I meant you should only delete whats inside the "php" folder, not the entire "src" folder.
If you deleted too many files now and can't restore them, please just uninstall the program and install it again.

**Comment by spidget** [comment] 2017-09-26 16:10
I didn’t delete the TagUI folder but I did reinstall t and it seems to work fine except it’s saying that it’s failing because my email and password for firertc is wrong. I’ll try to change those and get back to you with the results. Thanks for the help :)

**Comment by ccman32** [comment] 2017-09-26 21:31
@spidget Glad to hear that!
After you changed your password, would it be possible for you to tell me the password you used before or at least say if you used any special characters in it and which characters you used?
I've had the same problem before with passwords that contained backslashes but that should be fixed already. However, it could be possible that one or more symbols/characters still cause the same problem thus you can't use that password in combination with the FireRTC Caller ID Changer.

**Comment by ccman32** [comment] 2017-10-10 17:05
I will close this issue now because no further replies have been made.

**Closed as completed by ccman32** 2017-10-10 17:05 UTC
